replicaCount: 1

image:
  repository: ghcr.io/gkalian/site-gkalian
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-traefik"
    traefik.ingress.kubernetes.io/redirect-scheme: "https"
    kubernetes.io/ingress.class: "traefik"
  hosts:
    - host: gkalian.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: gkalian-tls
      hosts:
        - gkalian.com 

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80