name: Deploy static content to Github Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:   # allows you to run this workflow manually from the Actions tab

permissions:
  contents: write  # required for semantic-release to push tags
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  prepare:
    uses: ./.github/workflows/reusable-prepare.yml
    secrets: inherit

  build:
    needs: prepare
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      run_id: ${{ github.run_id }}
    secrets: inherit

  publish:
    needs: deploy
    uses: ./.github/workflows/reusable-publish.yml
    secrets: inherit
