jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    on:
      workflow_call:
    outputs:
      artifact-name: build-artifact-${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download version info
        uses: actions/download-artifact@v4
        with:
          name: version-info
          path: ./

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact-${{ github.run_id }}
          path: dist/
          retention-days: 1