jobs:

  prepare-version:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: bump-version
        run: |
          # Get current version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          
          # Bump patch version (1.0.0 -> 1.0.1)
          IFS='.' read -r -a version_parts <<< "$CURRENT_VERSION"
          NEW_VERSION="${version_parts[0]}.${version_parts[1]}.$((version_parts[2] + 1))"
          
          # Update package.json
          npm version $NEW_VERSION --no-git-tag-version --allow-same-version
          
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Upload version info
        uses: actions/upload-artifact@v4
        with:
          name: version-info
          path: |
            package.json
            CHANGELOG.md
